- nodecg-io-rcon/extension/index.ts
- nodecg-io-rcon/package-lock.json
- nodecg-io-rcon/package.json
- nodecg-io-rcon/rcon-schema.json
- package.json
This pull requests adds support for rcon clients.
npm package used: rcon-client
https://www.npmjs.com/package/rcon-client
https://github.com/janispritzkau/rcon-client
> Added RCON support

- nodecg-io-ws-client/extension/index.ts
- nodecg-io-ws-client/package-lock.json
- nodecg-io-ws-client/package.json
- nodecg-io-ws-client/tsconfig.json
- nodecg-io-ws-client/ws-schema.json
- nodecg-io-ws-server/extension/index.ts
- nodecg-io-ws-server/package-lock.json
- nodecg-io-ws-server/package.json
- nodecg-io-ws-server/tsconfig.json
- nodecg-io-ws-server/ws-schema.json
Added websocket integration.
This was way too much effort for such little payoff.
Node module used: 
https://github.com/websockets/ws
https://www.npmjs.com/package/ws
> Added Websocket Integration

- nodecg-io-ahk/ahk-schema.json
- nodecg-io-ahk/extension/AHK.ts
- nodecg-io-ahk/extension/index.ts
- nodecg-io-ahk/package-lock.json
- nodecg-io-ahk/package.json
- nodecg-io-ahk/tsconfig.json
This package will connect to a [HotkeylessAHK](https://github.com/sebinside/HotkeylessAHK) Server. 
using "node-fetch" package (already used for the intelliJ connector)
> Added AHK Connector

- nodecg-io-core/dashboard/panel.html
Just a little thing that annoyed me all the time.
> Add a key listener to the password input so you can confirm the password with enter

- nodecg-io-core/extension/instanceManager.ts
> enhancement/move error catching #20

- nodecg-io-ahk/extension/index.ts
- nodecg-io-core/extension/serviceBundle.ts
- nodecg-io-discord/extension/index.ts
- nodecg-io-intellij/extension/index.ts
- nodecg-io-rcon/extension/index.ts
- nodecg-io-spotify/extension/index.ts
- nodecg-io-twitch/extension/index.ts
- nodecg-io-twitter/extension/index.ts
- nodecg-io-ws-client/extension/index.ts
- nodecg-io-ws-server/extension/index.ts
> enhancement/service-boilerplate #22

- nodecg-io-core/extension/index.ts
> Stop all service clients when NodeCG is stopping

- .gitignore
I don't know why lerna creates this file, but its not important for GitHub repo
> Added Lerna Debug Log to .gitignore

- samples/xdotool/extension/index.ts
- samples/xdotool/package-lock.json
- samples/xdotool/package.json
- samples/xdotool/tsconfig.json
> Add xdotool sample bundle

- nodecg-io-ws-client/extension/index.ts
- nodecg-io-ws-client/package.json
Bumped version to 0.1.1
Added onClose, onMessage, onError and send message method.
(Fixes mistakes from #59)
> Added more functions to ws-client service

- README.md
- nodecg-io-irc/extension/index.ts
- nodecg-io-irc/irc-schema.json
- nodecg-io-irc/package-lock.json
- nodecg-io-irc/package.json
- nodecg-io-irc/tsconfig.json
Created IRC Client Service.
Fixed README. Watch for detail information in last commit `4069021`
If you wonder why 7 commit of StreamElements are in this pull request, I don't know why they are there but in the commits `bf7e1c6` and `30d3062` I deleted all files from StreamElements.
> Add IRC Client Service

- samples/discord-guild-chat/extension/index.ts
Used nodecg.log.info instead of console.log
> Fixed console.log in samples/discord-guild-chat

- README.md
- nodecg-io-slack/extension/index.ts
- nodecg-io-slack/package.json
- nodecg-io-slack/slack-schema.json
- nodecg-io-slack/tsconfig.json
- package-lock.json
- samples/slack/extension/index.ts
- samples/slack/package.json
- samples/slack/tsconfig.json
Added Slack WebAPI service with the official Slack package (@slack/web-api)
https://npmjs.com/package/@slack/web-api
> Added Slack WebAPI service

- nodecg-io-telegram/extension/index.ts
- nodecg-io-telegram/package.json
- nodecg-io-telegram/telegram-schema.json
- nodecg-io-telegram/tsconfig.json
- samples/telegram/extension/index.ts
- samples/telegram/package.json
- samples/telegram/tsconfig.json
Added telegram support.
Used package: 
https://www.npmjs.com/package/node-telegram-bot-api
https://github.com/yagop/node-telegram-bot-api
(types): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node-telegram-bot-api/index.d.ts
> Added telegram service

- nodecg-io-streamelements/extension/StreamElements.ts
- nodecg-io-streamelements/extension/index.ts
- nodecg-io-streamelements/package.json
- samples/streamelements/extension/index.ts
- samples/streamelements/package.json
- samples/streamelements/tsconfig.json
I will test these changes and then upload my sample project.
Tested:
> Made Streamelements use the node event system

- nodecg-io-streamelements/extension/StreamElements.ts
- nodecg-io-streamelements/package.json
- samples/streamelements/package.json
I was wondering why no events were fired... yea... the last commit really messed it up.
Version bump to 0.2.1
> Fixed a bug that stopped the SE-Service from working

- nodecg-io-streamelements/extension/StreamElements.ts
- nodecg-io-streamelements/package.json
- samples/streamelements/package.json
> Fixed a bug that stopped the SE-Service from working nr. 2

- samples/philips-hue/extension/index.ts
Replaced with capital S in nodecg.log.info Line 6
> Fixed Typo in Sample Phillipshue

- nodecg-io-core/extension/index.ts
Because of @derNiklaas Kappa: https://discordapp.com/channels/577412066994946060/577495219399032864/740920808792391760
> Log a warning if a bundle requires a non-existing service

- nodecg-io-streamelements/extension/StreamElements.ts
Fixes this bug: https://discordapp.com/channels/577412066994946060/577495219399032864/744997840593485934
> Fix StreamElements connect bug because of replicant serialization

- nodecg-io-core/extension/instanceManager.ts
> Unset bundle assignments on service instance deletion

- samples/websocket-client/extension/index.ts
- samples/websocket-client/package.json
- samples/websocket-client/tsconfig.json
Created a sample that connects to a websocket server and sends a ping every second.
> Created websocket sample

- nodecg-io-core/extension/persistenceManager.ts
- nodecg-io-core/extension/serviceBundle.ts
- nodecg-io-streamelements/extension/StreamElements.ts
- nodecg-io-streamelements/extension/index.ts
- nodecg-io-twitch/extension/index.ts
- nodecg-io-twitch/extension/twitchClient.ts
- samples/twitch-chat/extension/index.ts
Should fix #102 but needs more testing.
> Add simplficiation for twitch auto rejoin

- samples/sacn-sender/extension/index.ts
- samples/sacn-sender/package.json
- samples/sacn-sender/tsconfig.json
Icreated a sample for the sacn sender service
> Created sacn sender sample

- nodecg-io-core/extension/instanceManager.ts
> Stop service client when deleting a service instance

- nodecg-io-discord/extension/index.ts
This should fix @MelanX problem with cached messages.
> This should fix melans problem

- nodecg-io-discord/extension/index.ts
whoops, changed it in valdiateConfig instead of createClient. 😓
> Fix MelanX bug

- nodecg-io-spotify/extension/index.ts
Also addresses some smaller nitpicks.
> Stop refreshing of spotify access token when stopping client

- nodecg-io-core/extension/messageManager.ts
> Reduce code duplication in MessageManager

- README.md
Added a new never expiring discord invite
Fixes #166
> README: Update discord link

- README.md
- nodecg-io-twitch-api/extension/index.ts
- nodecg-io-twitch-api/extension/twitchApiClient.ts
- nodecg-io-twitch-api/package.json
- nodecg-io-twitch-api/tsconfig.json
- nodecg-io-twitch-api/twitch-api-schema.json
- samples/twitch-api/extension/index.ts
- samples/twitch-api/package.json
- samples/twitch-api/tsconfig.json
- samples/twitch-chat/extension/index.ts
> Add twitch-api service

- nodecg-io-twitch-api/package.json
- nodecg-io-twitch-chat/package.json
- nodecg-io-twitch-pubsub/package.json
- package-lock.json
This fixes the bug the library had related to the HypeTrain API.
> Bump twitch packages from 4.3.6 to 4.4.7

- nodecg-io-core/dashboard/serviceInstance.ts
- package-lock.json
Closes #175
Shows "Saving..." and "Succesfully saved." in the span that was previously only used for errors to show that it worked..
> Add service instance save confirmation to the dashboard

- nodecg-io-core/dashboard/utils/selectUtils.ts
Sorts the list alphabetically so it is way easier to find the service you need if you have a couple of service instances.
> Sort service instance list in dashboard

- nodecg-io-nanoleaf/extension/nanoleafUtils.ts
Fixed a small bug in the nanoleaf auth key retrieval function.
> Fix auth key retrieval bug.

- nodecg-io-core/dashboard/bundles.ts
- nodecg-io-core/dashboard/utils/selectUtils.ts
Does the same thing as #188 but without the bug that was the reason for f769cc1ef0ef67e020a8798fe3c193894237e4a6
> Sort instances in the dashboard, but now properly

- .gitignore
- .vscode/settings.json
- tsconfig.common.json
Several minor changes regarding the coding workflow in vs code:
* Generates js map files for easier dabugging
* Hides js and js map files
Close #181
> Add vs code debugging and js files hiding

- .gitignore
- .vscode/settings.json
- nodecg-io-template/extension/index.ts
- nodecg-io-template/extension/templateClient.ts
- nodecg-io-template/package.json
- nodecg-io-template/schema.json
- nodecg-io-template/tsconfig.json
- package.json
- samples/template/extension/index.ts
- samples/template/package.json
- samples/template/tsconfig.json
- tsconfig.common.json
Close #182 
* Adds template service ready to be implemented
* Adds template sample ready to be implemented
* Adds npm scripts `bs` and `bsb` ready to be used
> Add template service

- samples/irc/extension/index.ts
- samples/irc/package.json
- samples/irc/tsconfig.json
> Add IRC sample

- README.md
- nodecg-io-gsheets/extension/index.ts
- nodecg-io-gsheets/gsheets-schema.json
- nodecg-io-gsheets/package.json
- nodecg-io-gsheets/tsconfig.json
- samples/gsheets/extension/index.ts
- samples/gsheets/package.json
- samples/gsheets/tsconfig.json
> Add nodecg-io-gsheets service

- README.md
- samples/atem/extension/index.ts
- samples/atem/package.json
- samples/atem/tsconfig.json
- services/nodecg-io-atem/atem-schema.json
- services/nodecg-io-atem/extension/index.ts
- services/nodecg-io-atem/package.json
- services/nodecg-io-atem/tsconfig.json
Closes #139 
Merge documentation on https://github.com/codeoverflow-org/nodecg-io-docs/pull/80
> Add Atem Service

- nodecg-io-core/dashboard/authentication.ts
- nodecg-io-core/dashboard/crypto.ts
- nodecg-io-core/dashboard/esbuild.config.js
- nodecg-io-core/dashboard/main.ts
- nodecg-io-core/dashboard/serviceInstance.ts
- nodecg-io-core/dashboard/utils/deepCopy.ts
- nodecg-io-core/extension/__tests__/bundleManager.ts
- nodecg-io-core/extension/__tests__/instanceManager.ts
- nodecg-io-core/extension/__tests__/mocks.ts
- nodecg-io-core/extension/__tests__/persistenceManager.ts
- nodecg-io-core/extension/__tests__/serviceProvider.ts
- nodecg-io-core/extension/bundleManager.ts
- nodecg-io-core/extension/index.ts
- nodecg-io-core/extension/instanceManager.ts
- nodecg-io-core/extension/messageManager.ts
- nodecg-io-core/extension/persistenceManager.ts
- nodecg-io-core/extension/service.ts
- nodecg-io-core/extension/serviceBundle.ts
- nodecg-io-core/extension/serviceProvider.ts
- nodecg-io-core/extension/utils/result.ts
- services/nodecg-io-debug/esbuild.config.js
- utils/nodecg-io-twitch-auth/index.ts
Fix some typos and grammar in comments from core and dashboard.
Also removed some abbreviations
> Fix some typos in comments

- samples/streamelements-events/extension/index.ts
- samples/streamelements-events/graphics/index.html
- services/nodecg-io-streamelements/extension/StreamElements.ts
- services/nodecg-io-streamelements/extension/StreamElementsEvent.ts
Add streamelements sub bomb detection with replicant and extra sub gift filtering in onSubscriber Methods.
Closes #222
> feat: streamelements sub bomb detection

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/lint.yaml
Updates the used node.js and python versions in all workflows of this repository to node.js 18 and python 3.10.8.
> Update node.js and python versions in GitHub Actions

- samples/streamelements-events/extension/index.ts
Before this PR the username of test events has not been displayed correctly (`undefined`) because displayName was none.
This PR falls back in the sample to the original username of the underlying platform to fix this.
All bundles using the service should do this aswell
> Fallback to username if displayName is not available in StreamElements sample
