nodecg-io-rcon/extension/index.ts
Fixes #19
When there is a EventEmitter with no error handler attached and a error is emitted, the node will just exit: https://nodejs.org/api/events.html#events_error_events (second paragraph).
To fix this we just add a empty handler before connecting.
=> Fix RCON crashing nodecg

nodecg-io-streamdeck/extension/index.ts
By starting nodecg, nodecg can't find the schema, because the file name was set incorrectly.
=> Fixed StreamDeck Bug

.github/workflows/docs.yml
Workflow that automatically updates the docs once files are pushed to master.
Needs to be tested locally using [phishy/wflow](https://github.com/phishy/wflow) or [nektos/act](https://github.com/nektos/act).
Also the private access tokens for the docs repo must be generated and added as secrets to the repo as `${{ github.token }}` only has acces to the nodecg-io repo.
=> Actions workflow for building and updating docs

.github/workflows/lint.yaml, package.json
Moves bootstrapping using lerna into a seperate script called "bootstrap" instead of automatically being run using postinstall.
Before this PR the install routine would look like this:
1. npm installs lerna, eslint, prettier and stuff like that defined in
`package.json`
2. npm calls postinstall which then calls `lerna bootstrap`
3. Lerna bootstrap installs everything and writes the `package-lock.json` with all hoisted dependencies.
4. npm overwrites package-lock.json with the dependencies of
package.json, meaning lerna, eslint and so on. But this lock file
doesn't include all hoisted dependencies.
This is the reason why thef package-lock.json currently changed about
4000 lines depending if the dev used `npm install` or `npm run
postinstall`. This could be sawn here as an example: …
=> Move bootstrapping using lerna into a separate npm script

nodecg-io-core/dashboard/authentication.ts
Closes #12 
My hack mentioned in https://github.com/codeoverflow-org/nodecg-io/issues/12#issuecomment-643625054 didn't work and I didn't find any other way to find out whether nodecg has already loaded all bundles.
The last thing nodecg does after loading all the bundles is to start the webserver and therefore the dashboard so I thought why not just do it in the dashboard and relog using the password that was previously used to login.
Therefore after this PR the dashboard will try to login with the password that has been used to login once the dashboard reconnects to the nodecg webserver.
I think this solution is actually a bit cleaner than the one #12 because a bundle could read the environment variables or the cli flags but here it uses the normal login procedure so this solution is …
=> Automatic re-login in dashboard

nodecg-io-core/dashboard/bundles.ts
This fixes all these "Attempted to get value before Replicant had finished declaring." browser warnings that always made the browser console messy.
=> Check whether bundles replicant is declared in instance selector renderer

.gitignore, nodecg-io-core/dashboard/authentication.ts, nodecg-io-core/dashboard/bundles.ts, nodecg-io-core/dashboard/crypto.ts, nodecg-io-core/dashboard/main.ts, nodecg-io-core/dashboard/package.json, nodecg-io-core/dashboard/panel.html, nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-core/dashboard/tsconfig.json, nodecg-io-core/dashboard/webpack.config.js, nodecg-io-core/extension/bundleManager.ts, nodecg-io-core/extension/instanceManager.ts, nodecg-io-core/extension/persistenceManager.ts, package-lock.json
Fixes #30.
Adds webpack to build the dashboard because importing crypto-js using plain html and getting it to work in TS is not a beautiful experience and this way I can import the decryption logic from the main core.
=> Decrypt configs in dashboard and don't expose sensitive data in replicants

nodecg-io-core/dashboard/utils/selectUtils.ts
This fixes the jumping around while changing a bundle dependency where it always goes to the ahk bundle (because it is the first).
Now it will re-select the previously used bundle/service, e.g. when assigning a instance to twitch-chat it will stay there and not go to the ahk sample bundle.
=> Reselect bundles and bundle services when rerendering the bundle section

samples/midi-io/extension/index.ts, samples/midi-io/package.json, samples/midi-io/tsconfig.json
Created a sample for simultaneous midi input and output with a clean branch
=> fixed branch issues for new sample

nodecg-io-intellij/extension/intellij.ts
I just realised that I added this feature to the intellij plugin more than two month ago and never opened a pull request for this here.
=> Add a way to get PID of IntelliJ

samples/rcon-minecraft/extension/index.ts, samples/rcon-minecraft/package.json, samples/rcon-minecraft/tsconfig.json
This is a simple rcon-minecraft sample.
It sends /list to a minecraft server, prints the output and then performs /say nodecg-io speaking here!
=> Added simple rcon sample

nodecg-io-obs/extension/index.ts
The obs client throws a object when a error happens. When the framework catches the error it just tries to convert it to a string but when doing this with a object it just produces `[object Object]`.
This PR catches the exception and extracts the actual error message of the object to solve this, as it is also done in the `validateConfig` method.
=> Properly format obs client creation errors in createClient

README.md
- Adds serial port and TIANE to the list of services in the readme
- Generalizes the repository structure because it was a burden to maintain and having all the services in there doesn't provide much value to people trying to understand the structure
=> Add serial port and tiane to readme, generalize repo structure

nodecg-io-reddit/extension/index.ts, nodecg-io-reddit/package-lock.json, nodecg-io-reddit/package.json, nodecg-io-reddit/reddit-schema.json, nodecg-io-reddit/tsconfig.json, package-lock.json, samples/reddit-msg-read/extension/index.ts, samples/reddit-msg-read/package.json, samples/reddit-msg-read/tsconfig.json
Currently `reddit-ts` is installed from my github because of an import error in `httyp`. This will be changes when [#3](https://github.com/aelesia/npm-http/pull/3) is merged.
=> Add a reddit service

samples/spotify-current-song/extension/index.ts, samples/spotify-current-song/package.json, samples/spotify-current-song/tsconfig.json
Adds missing sample for the spotify service as noted in #111.
Displays the currently playing song in the console.
Sample doc PR: https://github.com/codeoverflow-org/nodecg-io-docs/pull/39
=> Add sample for spotify

nodecg-io-irc/package.json, nodecg-io-serial/package.json, nodecg-io-telegram/package.json
Moves irc, serial and telegram type dependencies that are exposed from `devDependencies` to `dependencies` so that they can be imported properly once these packages are published.
=> Move exposed type deps from devDependencies to dependencies

nodecg-io-core/dashboard/authentication.ts, nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-core/extension/instanceManager.ts
A instance should propably not be named with an empty string.
=> Disallow empty instance names and show instance creation errors

samples/serial/extension/index.ts, samples/streamdeck-rainbow/extension/index.ts, samples/websocket-client/extension/index.ts
If the streamdeck was once available a timeout gets registered but never cleared.
This makes problems e.g. when the instance gets deleted: https://discord.com/channels/577412066994946060/577495348898168832/793590990475755550
=> Clear timeouts/intervals in sample bundles

nodecg-io-core/dashboard/authentication.ts, nodecg-io-core/dashboard/panel.html, nodecg-io-core/extension/messageManager.ts, nodecg-io-core/extension/persistenceManager.ts
Adds a notice to the dasboard that explains that the password is freely choosable on first startup.
It is not clear that it is setting the password there so this should clarify things.
=> Add password notice in dashbord on first startup

nodecg-io-streamelements/package.json, package-lock.json
I've upgraded the socket.io-client in #147 to v3 but the streamelements endpoint seems to only support v2.
=> Downgrade streamelements socket.io client to v2

nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-core/extension/instanceManager.ts
Previously errors by the `createClient` methods were just logged to the console but not displayed in the dashboard like the config validation errors.
=> Display createClient errors on the dashboard

nodecg-io-core/dashboard/package.json, nodecg-io-core/package.json
`typescript` is only needed to execute the compiler but not for execution. It is also not needed for imports. Therefore it should be a dev dependency like it is in all other packages instead of the core and the dashboard for whatever reason.
=> Move typescript to devDependencies in core and dashboard

samples/discord-guild-chat/extension/index.ts
The `ready` event [doesn't seem to fire consistently](https://discord.com/channels/577412066994946060/577495219399032864/798265088954990632) and therefore shoudn't be used.
=> Remove ready handler from discord sample

samples/twitch-chat/extension/index.ts
It created spam in streams and also everybody who didn't want to spam the twitch chat commented it out anyway.
=> Remove sending message from twitch-chat sample

nodecg-io-spotify/extension/index.ts, nodecg-io-spotify/package.json, nodecg-io-spotify/spotify-schema.json, package-lock.json
(VS Code GitHub extension messed up branch name LULW)
Saves the spotify refresh token so that it can be re-used to create a access token at startup. That way we only need to open a tab to login once (the first start) instead of every time.
This can also be used as a workarround to get spotify working on a headless server.
Also updates spotify typings to 5.0.0 (from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50333).
=> Save spotify refresh token

nodecg-io-core/.npmignore, nodecg-io-core/dashboard/package.json
When packing nodecg-io-core it would include the dashboard, which has a symlink to the core in the node-modules directory which resulted in a infinte loop when trying to pack the core.
The dashboard will now also be published to npm and in the planed yeoman generator, which will install releases of nodecg-io, will download it separately.
=> Don't publish dashboard with core

.eslintrc.js, nodecg-io-ahk/extension/AHK.ts, nodecg-io-ahk/extension/index.ts, nodecg-io-android/extension/android.ts, nodecg-io-android/extension/index.ts, nodecg-io-core/dashboard/bundles.ts, nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-philipshue/extension/index.ts, nodecg-io-xdotool/extension/index.ts, nodecg-io-xdotool/extension/xdotool.ts, samples/midi-input/helperscripts/listDevices.ts, samples/twitch-pubsub/extension/index.ts
NodeCG bundles should use the integrated nodecg logger and while developing you easily forget it and use `console.log`/`console.error` which may be forgotten and left in the code.
This also introduces a inconsistency because sometimes the nodecg logger and sometimes the `console.log` is used.
To deal with this, this PR adds a eslint rule to treat `console.log` as a warning to ensure that the nodecg logger is used before code is merged. While developing and trying things out you should be still able to use `console.log` if you wish to, that's why only a warning and not an error.
=> Warn on console.log usage and embrace nodecg logger

nodecg-io-twitch-pubsub/extension/index.ts, nodecg-io-twitch-pubsub/extension/pubSubClient.ts
Previously the scopes of the auth token was not really checked and resulted in a crash once the service instance was assigned to a bundle. This was because only the add handler functions that were used by the bundle caused a api call with the credential and this may fail because of missing scopes on the token. This adds a check which will make sure that the token has sufficient scopes and will show an error in the UI if not.
Also adds the possibility to stop the pubsub client, which was previosly not given.
=> Verify auth token in pubsub service and add way to stop it

nodecg-io-twitch-pubsub/extension/pubSubClient.ts
Reverts token scope check from #186, it sadly didn't work and always threw the error because it can't listen for a empty array of topics :disappointed: .
=> Revert pubsub token scope check

nodecg-io-nanoleaf/extension/index.ts, nodecg-io-nanoleaf/index.ts, nodecg-io-nanoleaf/package.json
Does a similar thing to the core index.ts to export classes and function which is not possible through extenstion/index.ts because it already has a default export for the nodecg function.
Allows `import {NanoleafUtils} from "nodecg-io-nanoleaf"` to work as intented.
=> Fix export of NanoleafUtils through index.ts file

nodecg-io-core/extension/bundleManager.ts, nodecg-io-core/extension/index.ts, nodecg-io-core/extension/serviceProvider.ts, nodecg-io-core/extension/types.d.ts, nodecg-io-core/index.ts
At the initial creation of the framework it was intented for bundles to provide a callback which would be called with undefined or the client if the client changed. On top of this `ServiceClientWrapper` was built which allowed bundles to have a separate callback for when a client is available or unavailable. `ServiceClientWrapper` used the previously used callback which in retrospect was just an ugly addition.
This PR refactors it to be more integrated with the framework by completely removing the old callback with it and renaming it to `ServiceProvider` which imo is a way better name.
Also now the `EventEmitter` is now in a variable so that it doesn't feel so bloated with all the `EventEmitter` functions when using InteliSense on it.
EDIT: there still seems to be a big in this it …
=> Refactor ServiceClientWrapper

nodecg-io-irc/extension/index.ts, nodecg-io-irc/package.json, package-lock.json
Fixes IRC Client hangs when using a wrong password #120. Now retries work as intented and it therefore also fails on wrong passwords.
Also removes irc connection check from `validateConfig` because it is the complete same check that `createClient` would do.
=> Fix usage of irc retry limit

nodecg-io-youtube/extension/index.ts
Fixes #212. The problem is that the google oauth2 api only returns a refresh token if a confirmation prompt was displayed to the user. Previously if you logged in once it would use the session and automatically authenticate you. But then you don't have a refresh token and it fails because of that after about an hour.
This creates the problem that everytime you need to select your Google account and click "OK" but I will create a followup PR to save the refresh token so you don't need to login each time and also it doesn't create a browser tab each time.
=> Fix youtube token refreshing by always prompting user for consent

nodecg-io-core/extension/index.ts, nodecg-io-core/extension/persistenceManager.ts, nodecg-io-spotify/extension/index.ts, nodecg-io-youtube/extension/index.ts, nodecg-io-youtube/youtube-schema.json
=> Save youtube refresh token in config for re-use

nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-core/extension/index.ts, nodecg-io-core/extension/instanceManager.ts, nodecg-io-core/extension/persistenceManager.ts, nodecg-io-core/extension/serviceBundle.ts, nodecg-io-core/extension/types.d.ts, nodecg-io-curseforge/extension/index.ts
With this services that don't require a config like curseforge or the debug service (#205) will be automatically set and created.
That way you don't need to manually click "save" which can be forgotten.
Also shows in the UI that these services don't need any configuration.
=> Automatically set instances with no required config

nodecg-io-core/dashboard/serviceInstance.ts
#211 didn't hide that button and when pressing it, it would obviously create an error.
=> Hide save button when selecting a non configurable service

nodecg-io-core/extension/index.ts, nodecg-io-core/extension/instanceManager.ts
Closes #217.
Rewrites `updateInstanceConfig` to write the config before it returns, if no validation is needed. That way we don't create promises using the event loop that may be slower than us allowing saving which then could result in corrupted configs, as we saw in #217.
=> Fix race condition in PersitsenceManager

nodecg-io-core/extension/index.ts
Fixes all the errors about not being able to stop clients and "... is not defined on value undefined" for all services that aren't configured properly
=> Only stop client on exit when it is defined

nodecg-io-core/dashboard/authentication.ts
When many bundles are loaded nodecg takes it's time after a connection till all replicants are usable, which are required to do the login. Therefore this PR waits for about 200ms after the connection is established to let nodecg connect fully.
=> Fix instabilities with automatic login after restarts

.github/workflows/docs.yml
When we update a `release/x.y` branch the documentation on the same branch of the docs repo should also be updated.
=> Run update doc action also on release branches

nodecg-io-core/dashboard/crypto.ts, nodecg-io-core/extension/persistenceManager.ts
Could be a solution for #231, was definitly not intented the way it was.
If you added a bundle you would first need to do an action that saved the config because otherwise it would be still the one from the last start without the new bundle. This was not noticied because usually you first create a new instance for the bundle and then you don't notice this behaviour.
=> Save config after all service instances have been loaded at startup

.gitignore
This file is created by the nodecg-io cli when you create a install and saves what you have selected there. In case you create a development install git will say that this file is untracked because it is not checked in and not gitignored.
This file should not be commited so this PR adds it to the `.gitignore` file.
=> Add install.json from nodecg-io-cli to .gitignore

nodecg-io-core/configschema.json, nodecg-io-core/extension/persistenceManager.ts
Closes #236 
Gets password using nodecg bundle config and automatically logs in after startup has finished if automatic login is configured.
Docs PR: https://github.com/codeoverflow-org/nodecg-io-docs/pull/59
=> Implement automatic login after startup

utils/nodecg-io-twitch-auth/package.json
`nodecg-io-twitch-auth` has its main file directly in `index.{ts,js}`, which is the default. But it was set to `extension/index` which does not exist and is incorrect. This happend because we I've copied `package.json` from some other package and didn't notice this.
Previous node.js versions simply ignored this but v16 and newer report this as a [runtime deprecation](https://nodejs.org/api/deprecations.html#DEP0128).
=> Remove main entry from twitch-auth package.json

nodecg-io-android/extension/android.ts, nodecg-io-curseforge/extension/curseforgeClient.ts
* Added some methods to query file information for the android service using shell commands.
This uses shell commands instead of the app as with shell commands it's possible  to access more files on the system that an app could on a non-rooted phone.
* Clarify difference between `categoryID` and `sectionId` in the curseforge service.
=> Few changes

nodecg-io-core/extension/instanceManager.ts, nodecg-io-core/package.json, package-lock.json
Previously a instance would be deleted from InstanceManager and after that all bundles that used the instance that gets deleted would be unset.
This caused an error in the handler re-registration process which would be logged but otherwise didn't cause any problems.
=> Unset service instance usages before deleting an instance

nodecg-io-intellij/extension/index.ts, nodecg-io-intellij/extension/intellij.ts, nodecg-io-intellij/intellij-schema.json
The IntelliJ schema mentions that it defaults to `127.0.0.1:19524` if no address is given.
This makes sense as most will connect the service to the IntelliJ instance running on the same host.
However the schema requires a value and also the code doesn't check for `undefined` and thus doesn't provide the default if the value is missing.
This PR implements the default value by using it if no value is provided and removing `address` from the required fields list of the JSON schema.
=> Implement `localhost` default address for IntelliJ service config

nodecg-io-elgato-light/extension/elgatoLight.ts, nodecg-io-elgato-light/extension/elgatoLightClient.ts, nodecg-io-elgato-light/extension/index.ts, nodecg-io-elgato-light/extension/lightData.ts, nodecg-io-elgato-light/package.json, nodecg-io-elgato-light/schema.json, nodecg-io-elgato-light/tsconfig.json, samples/elgato-light/extension/index.ts, samples/elgato-light/package.json, samples/elgato-light/tsconfig.json
Closes #118. Does not use any external elgato light npm library because the're are all not up to date and we only need two HTTP requests...
=> elgato-light service for Keylights and light stripes.

nodecg-io-core/extension/serviceBundle.ts, nodecg-io-curseforge/extension/index.ts, nodecg-io-curseforge/schema.json, nodecg-io-debug/extension/index.ts, nodecg-io-debug/schema.json
The curseforge and debug service don't require any configuration and therefore the current JSON schema is empty.
This is unneeded because the schema isn't used to validate the config as there is no config.
To make these services easier we can safely remove the schemas as they are optional anyway.
=> Remove JSON schemas from configuration-less services

samples/streamelements-events/extension/index.ts, samples/streamelements-events/package.json, services/nodecg-io-streamelements/extension/StreamElements.ts, services/nodecg-io-streamelements/extension/StreamElementsEvent.ts, services/nodecg-io-streamelements/extension/index.ts, services/nodecg-io-streamelements/package.json, services/nodecg-io-streamelements/streamelements-schema.json
This PR adds a new field ``handleTestEvents`` to the SE config which controls whether it should also fire test events.
Also bumps the version to ``0.2.1`` for the sample and nodecg-io-streamelements
=> Feature: Update nodecg-io-streamelements to include test events

.github/workflows/docs.yml
All GitHub Actions runs triggered by dependabot have no access to secrets for security reasons.
Because of this our documentation update action is failing when dependabot merges a pull request.
This pr adds a check to the action. Now it will only run if it was not triggered by dependabot.
=> Don't run docs update action for events caused by dependabot

samples/twitch-addons/package.json
The bundle dependency on the `nodecg-io-twitch-addons` bundle in the sample bundle was still referencing the template service.
Because of this in some instances the `twitch-addons` sample bundle failed to load because it was loaded before the service.
=> Fix twitch-addons sample bundle dependency

services/nodecg-io-telegram/extension/index.ts
Closes #267
Previously the telegram library automatically would enable bluebird promise cancellation. It is recommended to set the `NTBA_FIX_319` environment variable to disable automatic activation and only enable it if needed. We don't use promise cancellation arround here and anyone using our telegram service propably doesn't either. If this is the case they should enable it themselfs.
=> Disable deprecated automatic promise cancellation in telegram

.github/workflows/docs.yml, .scripts/build-docs.py, README.md, nodecg-io-core/extension/__tests__/mocks.ts
Check https://github.com/codeoverflow-org/nodecg-io/issues/266 for more details.
Replaces `master` with `main` in GitHub Action workflows, our documentation script and the readme.
=> Update Action workflows and docs script for master to main renaming

.gitignore, nodecg-io-core/dashboard/main.ts, nodecg-io-core/dashboard/package.json, nodecg-io-core/dashboard/panel.html, nodecg-io-core/dashboard/serviceInstance.ts, nodecg-io-core/package.json, package-lock.json, services/nodecg-io-debug/dashboard/debug-helper.html, services/nodecg-io-debug/dashboard/debug-helper.ts, services/nodecg-io-debug/package.json, services/nodecg-io-debug/webpack.config.js
Closes #311.
Monaco uses some newer browser features that are not available on old chromium versions like the one embedded in OBS. To fix this (and also fix our kinda hacky loading of monaco through a relative fs mount to the root  `node_modules`) we can load monaco through webpack.
I've activated webpack caching because webpack is now actually processing more than 5 files and using it the build time can be reduced from ~6s to 1.5s per webpack project. The caches take up about 12MB per project, so 24MB in total, which is okay I think.
=> Load monaco-editor using webpack instead of monacos own loader

samples/twitch-addons/extension/index.ts, services/nodecg-io-twitch-addons/extension/twitchAddonsClient.ts
Sadly, since Javascript variables (and object properties) can't start with numbers, I made 7tv's property on [EmoteCollection](https://github.com/codeoverflow-org/nodecg-io/blob/de1c46d49e10fe29310526f8ec9320a18569495c/services/nodecg-io-twitch-addons/extension/twitchAddonsClient.ts#L436) 'stv' so users can access the collection with **`emotes.stv` instead** of using a string key with access through `emotes["7tv"]`
```ts
var emotes = await client.getEmoteCollection... // Get emotes
// Easier to access:
emotes.stv.find(v => v.name === "docSpin")
// An annoyance to access:
emotes["7tv"].find(v => v.name === "docSpin")
```
Since it's common to make 7TV optional (at least in the chat clients I've looked over), I also modified the second parameter of getEmoteCollection (previously a boolean …
=> Add 7TV emotes to nodecg-io-twitch-addons

nodecg-io-core/dashboard/serviceInstance.ts, services/nodecg-io-debug/dashboard/debug-helper.ts
Introduced by #312. The null assertions were ment for temporary testing and I forgot to remove them....
=> Remove monaco null assertions to fix linter warnings

services/nodecg-io-debug/package.json, services/nodecg-io-nanoleaf/package.json
The debug service exposes the `NodeCG` type with its constructor and nanoleaf with the `NanoleafUtils.retrieveAuthKey` method.
Because of this the generated `.d.ts` files import `nodecg-types` and we need to make it a production dependency as it is needed to be able to use the typings when e.g. adding it as a dependency to a bundle once it has been released.
=> Move nodecg-types to normal dependencies for debug and nanoleaf service

nodecg-io-core/dashboard/package.json, services/nodecg-io-debug/package.json
Starting with #312 monaco is included in the javascript bundles that are generated by webpack and does not get loaded out of the `node_modules` directory anymore. This means we can move it to `devDepencencies` as it is only needed during build time and save about 80 MiB of space in a production install, reducing its size (with all services installed) from 328 MiB to 248 MiB.
=> Move monaco-editor to `devDependencies`

services/nodecg-io-streamelements/extension/StreamElementsEvent.ts
StreamElements sends out `name` instead of `username` in the onTest Event.
This adds the correct type for that specific event.
=> Add StreamElementsTestEventData interface for correct "onTest" types.

nodecg-io-core/dashboard/package.json
=> Actually move monaco-editor to `devDependency` in dashboard

.github/workflows/ci.yml
Closes #235.
I've decided to do both: publishing tarballs and the compilation results.
Extracting the tar files in the action step isn't that much work and we still can change it in the future.
Also uploads the compilation results as a Actions artifact so that the publish job doesn't need to recompile the whole project again.
Published version of this branch: https://github.com/codeoverflow-org/nodecg-io-publish/tree/feat/235-dev-publish
=> Publish tarballs and compilation results on push

nodecg-io-core/dashboard/package.json, package-lock.json, services/nodecg-io-debug/package.json
Reverts d1da66337a6c0c141d174bd5aaa8a4be4baf545a / #377
There is some change with `0.30.0` that results in a build output by webpack that
is incompatible with the Chromium version that is used by custom OBS Docks.
I don't know what the exact problem is yet with this specific update,
this PR is just here to fix this bug till I figure out if we can make
the new version compatible with OBS Docks or not.
=> Downgrade monaco-editor from 0.31.1 to 0.30.1

.github/workflows/ci.yml, .github/workflows/docs.yml
Because events triggered by dependabot don't have access to encrypted secrets we don't update the documentation and tarballs for commits by dependabot.
However this means that the documentation and tarballs can be pretty outdated till the next manual commit.
Becuase we have all dependabot PRs at Saturday this PR adds a cronjob on Saturday evening to update the docs/tarballs after all PRs by dependabot have been merged.
Discussion on Discord about this: https://discord.com/channels/577412066994946060/581828193196179457/920977923991814195
=> Automatically update docs and tarballs using a cronjob

nodecg-io-core/extension/persistenceManager.ts
Fixes #365.
If automatic login fails and nodecg-io is not loaded afterwards this will still display a error. This happens when e.g. the password set in the automatic login config is wrong.
However if automatic login fails and nodecg-io is loaded afterwards just a warning will be logged with this PR. This is the case when the dashboard reconnects after a restart and loggs back in.
=> Just log a warning when trying automatic login, but nodecg-io is already loaded

.eslintrc.js, .prettierrc.js, .vscode/settings.json, jest.config.js, jest.config.mjs, nodecg-io-core/dashboard/esbuild.config.js, nodecg-io-core/jest.config.js, nodecg-io-core/jest.config.mjs, package.json, services/nodecg-io-curseforge/extension/curseforgeClient.ts, services/nodecg-io-dbus/extension/ratbag.ts, services/nodecg-io-debug/esbuild.config.js, services/nodecg-io-twitch-addons/extension/twitchAddonsClient.ts
- Add JSDoc types to `jest.config.js`, `.eslintrc.js` & `.prettierrc.js`
- Set more prettier configs explicitly to circumvent an issue I experienced with the prettier
vscode extension, where it would format some stuff based on my global preferences
and not the defaults.
- Use Set in `esbuild.config.js`
- Format all js and ts files
- Use module syntax in jest config
- Automatically add packages with jest config to root jest projects
- Add .mjs extension to files formatted by prettier
- Enable type checking JS files project wide
Tim
=> chore:Format configs & scripts

services/nodecg-io-googleapis/extension/index.ts, services/nodecg-io-googleapis/package.json, services/nodecg-io-spotify/extension/index.ts, services/nodecg-io-spotify/package.json
Saves a dependency from googleapi and spotify services
=> fix: replace express.Router references with nodecg.Router

services/nodecg-io-googleapis/extension/index.ts, services/nodecg-io-googleapis/googleapis-schema.json, services/nodecg-io-spotify/extension/index.ts, services/nodecg-io-spotify/spotify-schema.json
- Adds an optional config option `httpsRedirect` to spotify and googleapis services
- Makes googleapis service use NodeCG's `config.baseURL` for redirect URL as the spotify service already does
=> Make OAuth redirect URLs match nodecg's baseUrl & protocol

.github/workflows/ci.yml, .scripts/ci-nodecg-integration.mjs
Ensures that nodecg-io is loadable on Windows automatically by CI.
We already have this for Linux as of #327, this PR just makes it compatible with Windows and runs it in CI.
The timeout command returns a non-negative exit code for some reason when the timeout is reached so I've ditched it and implemented the timeout in the node.js script.
The test with windows is pretty slow in CI so I've at least cached the NodeCG installation making it (more or less) acceptable.
=> Run NodeCG test in CI on Windows

.github/workflows/ci.yml
`windows-latest` was recently switched to be an alias for `windows-2022` instead of `windows-2019`. This causes the recent build failures because node-gyp doesn't work properly with Visual Studio 2022 yet. This PR changes it back to `windows-2019` to fix build failures till node-gyp fully supports Visual Studio 2022.
=> Use windows-2019 instead of windows-latest in CI

services/nodecg-io-midi-input/extension/index.ts, services/nodecg-io-midi-output/extension/index.ts
Fix for https://discord.com/channels/577412066994946060/577495348898168832/958791971386843147
=> Priorize exact midi device name match in case of an ambiguous pattern

services/nodecg-io-midi-input/extension/index.ts
See https://github.com/codeoverflow-org/nodecg-io/pull/531/files#r847220324
=> Find midi input devices by applying pattern to input instead of output devices

services/nodecg-io-obs/extension/index.ts
Now outputting correct error when the connection to obs can't be established
Before:
```
error: [nodecg-io-core] The "obs" service with the name "obs" produced an error while creating a client: undefined
```
After:
```
error: [nodecg-io-core] The "obs" service with the name "obs" produced an error while creating a client: connect ECONNREFUSED 127.0.0.1:4444
```
=> Fix undefined error message in obs service

samples/streamelements-events/extension/index.ts, services/nodecg-io-streamelements/extension/StreamElements.ts
I missed the usage of a wrong eventName and with that an inconsistant naming of the onTestSubscriber function.
=> fix: Use correct eventName and event function name in Stream Elements

README.md, package-lock.json, samples/opentts/extension/index.ts, samples/opentts/graphics/index.html, samples/opentts/graphics/index.ts, samples/opentts/package.json, samples/opentts/tsconfig.json, services/nodecg-io-opentts/extension/index.ts, services/nodecg-io-opentts/extension/openTtsClient.ts, services/nodecg-io-opentts/package.json, services/nodecg-io-opentts/schema.json, services/nodecg-io-opentts/tsconfig.json
Closes #288 
It is possible to add google cloud tts. But since it requires billing to be active, we only added opentts for now.
=> feat: Add opentts service and sample

nodecg-io-core/dashboard/package.json, package-lock.json, services/nodecg-io-debug/package.json, services/nodecg-io-nanoleaf/package.json
`nodecg-types` is only used when compiling typescript at dev time and not required when running nodecg-io. This PR moves it to be a dev dependency everywhere because it was mistakenly a prod dependency in some bundles.
=> Move nodecg-types to be a dev dependency everywhere

.github/dependabot.yml
Merging dependabot PRs each week has kinda become a burden. Since there is not that much development currently anyway, updating the dependencies only once a month is fine, and I can hopefully use the saved time to do actual work.
=> Only run dependabot once a month

package-lock.json, services/nodecg-io-googleapis/package.json
The `nodecg-io-googleapis` service depends on the `googleapis` package for the service implementation.
The service was added in ed7eb2f71807378dae9a5462f7a481df126b2987 with an additional dependency to `@types/gapi` for types. However the used `googleapis` package provides its own typings out of the box and `@types/gapi` is for the outdated `gapi` package which is not used here.
Removes the mentioned unused typing package as it is not used.
=> Remove @types/gapi dependency from googleapis service

package-lock.json
Fixes #832 by updating the midi dependency to use the fix provided in https://github.com/Julusian/node-midi/pull/5.
=> Update node midi dependency in lock file

.github/workflows/ci.yml
Makes twitch services work in generated bundles of nodecg-io-cli development environments. See https://github.com/codeoverflow-org/nodecg-io/discussions/893#discussioncomment-5280262 for a more detailed explanation.
=> Patch version of twitch-auth package in published tarballs

.scripts/ci-nodecg-integration.mjs
Since NodeCG v2 the NodeCG integration test that ensures all bundles are öoadable by the current NodeCG version is flaky under windows. This is caused by NodeCG being stopped before even having a chance to load all
bundles. Seems like NodeCG v2 takes longer to start up so this PR increases the timeout from 15 seconds to 20 seconds.
=> Increase timeout in NodeCG integration test to fix test flakiness

services/nodecg-io-streamelements/extension/StreamElements.ts, services/nodecg-io-streamelements/extension/StreamElementsEvent.ts
Add event listener to `event:update`, which is the new endpoint that stream elements uses to display all replays of previous real events.
=> fix: Stream Elements replay event not working

.github/workflows/ci.yml
Cause for failure of https://github.com/codeoverflow-org/nodecg-io/actions/runs/5638130058
=> Do not publish tarballs in CI for tags

nodecg-io-core/dashboard/package.json
Previously no `files` key was specified in the package.json of the dashboard.
Because of this only the source files were added to the dashboard v0.3.0 tarball.
This PR updates the package.json to include the built version that is used by the production installations that are made using the nodecg-io-cli.
After this PR has been merged it will be backported to the `release/0.3` branch and v0.3.1 of the dashboard will be released.
=> Add built assets to tarball of the dashboard

samples/streamelements-events/extension/index.ts, services/nodecg-io-streamelements/extension/StreamElements.ts, services/nodecg-io-streamelements/extension/StreamElementsEvent.ts, services/nodecg-io-streamelements/extension/index.ts, services/nodecg-io-streamelements/streamelements-schema.json
Closes #969, closes #970, closes #971 
The specific Test-Events (e.g. `onTestSubcriber`) got removed and are now getting published through the normal event handlers. The test events are identifiable by the `isMock` flag.
Also the subscriber event data now has an optional flag called `isFromSubBomb`, which is set (and true) when this subscriber is.. from a subbomb.
=> StreamElements: Fix API, remove specific Test-Events and add flag for subbomb subscriber event data

.github/workflows/ci.yml, .husky/pre-commit, nodecg-io-core/dashboard/bundles.ts, nodecg-io-core/dashboard/panel.html, nodecg-io-core/extension/utils/logger/index.ts, package-lock.json, package.json, samples/gametts/graphics/index.html, samples/opentts/graphics/index.html, samples/streamelements-events/graphics/index.html, services/nodecg-io-ahk/extension/AHK.ts, services/nodecg-io-android/extension/android.ts, services/nodecg-io-debug/dashboard/debug-helper.html, services/nodecg-io-elgato-light/extension/elgatoLight.ts, services/nodecg-io-nanoleaf/extension/nanoleafClient.ts, services/nodecg-io-xdotool/extension/xdotool.ts
With prettier v3 pretty-quick does not work anymore. It hasn't had a new commit for two years so it is unlikely it will ever support prettier v3.
So this PR migrates the pre-commit hook to use lint-staged which also supports running eslint on the changed files before a commit and is maintained.
=> Switch from pretty-quick to lint-staged for auto formatting on commit
